In [3]:
import pandas as pd
import numpy as np
import PublicDataReader as pdr

In [8]:
hcode = pdr.code_hdong()
hcode = hcode.loc[(hcode['시도코드']=='26') & (hcode['시군구코드']!='') & (hcode['읍면동명']!='') & (hcode['말소일자']=='')]
hcode = hcode[['시군구코드','시군구명','행정동코드', '읍면동명']]
hcode.columns = ['gcode', 'gname', 'hcode', 'hname']
inner1 = pd.read_csv("project/4_대상지_관내유입_생활인구_현황.csv", sep="|", dtype={'std_ym': str, 'id': str, 'inflow_cd': str}, encoding="utf-8")
inner1 = pd.merge(inner1, hcode, "inner", left_on="inflow_cd", right_on="hcode")
inner1.head()

출처: 행정기관(행정동) 및 관할구역(법정동) 변경내역(2024.8.1. 시행)

,std_ym,id,roadnm,inflow_cd,regists,pop,gcode,gname,hcode,hname
0,202201,1,갈맷길2-1코스,2620065000,주거,0.0,26200,영도구,2620065000,동삼제1동
1,202201,10,갈맷길2-1코스,2620065000,주거,0.0,26200,영도구,2620065000,동삼제1동
2,202201,1124,갈맷길2-1코스,2620065000,주거,0.0,26200,영도구,2620065000,동삼제1동
3,202201,1125,갈맷길2-1코스,2620065000,주거,0.0,26200,영도구,2620065000,동삼제1동
4,202201,14908,갈맷길2-1코스,2620065000,주거,0.0,26200,영도구,2620065000,동삼제1동

In [9]:
group = inner1.groupby(['std_ym','roadnm','gcode','gname','regists']).agg({'pop': np.sum}).reset_index().sort_values(by=['std_ym', 'gcode'])
group.to_csv("4_대상지_관내유입_생활인구_현황(합계).csv", sep="|", encoding="utf-8", index=False)

In [4]:
hcode = pdr.code_hdong()
hcode = hcode.loc[(hcode['시군구코드']!='') & (hcode['읍면동명']!='') & (hcode['말소일자']=='')]
hcode = hcode[['시도코드','시도명']]
hcode.columns = ['scode', 'sname']
outer1 = pd.read_csv("project/4_대상지_관외유입_생활인구_현황.csv", sep="|", dtype={'std_ym': str, 'id': str, 'inflow_cd': str}, encoding="utf-8")
outer1 = pd.merge(outer1, hcode, "inner", left_on="inflow_cd", right_on="scode")
outer1.head(3)

출처: 행정기관(행정동) 및 관할구역(법정동) 변경내역(2024.8.1. 시행)

   std_ym id    roadnm inflow_cd regists  pop scode  sname
0  202201  1  갈맷길2-1코스        11      주거  0.0    11  서울특별시
1  202201  1  갈맷길2-1코스        11      주거  0.0    11  서울특별시
2  202201  1  갈맷길2-1코스        11      주거  0.0    11  서울특별시

In [10]:
group = outer1.groupby(['std_ym','roadnm','scode','sname','regists']).agg({'pop': np.sum}).reset_index().sort_values(by=['std_ym', 'scode'])
group.to_csv("4_대상지_관외유입_생활인구_현황(합계).csv", sep="|", encoding="utf-8", index=False)